[package]
name = "csv-read-test"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
flate2 = "1.0.34"
gzip = "0.1.2"
image = "0.25.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
